name: Hprofile Actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
       # run: echo "Workflow works!"
        uses: actions/checkout@v4

      - name: maven test
        run: mvn test
      
      - name: Checkstyle
       # run: mvn checkstyle:checkstyle
        run: nikitasavinov/checkstyle-action@master
      - name: Set Java 11 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
