name: Vprofile Actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
       # run: echo "Workflow works!"
        uses: actions/checkout@v4

      - name: maven test
        run: mvn test
      
      - name: Install mvn plugin
        run: mvn my.plugin.groupId:foo-maven-plugin:1.0.0:bar
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'